INSERT into players (id, name) values (default, 'Джокович');
INSERT into players (id, name) values (default, 'Федерер');
INSERT into players (id, name) values (default, 'Надаль');
INSERT into players (id, name) values (default, 'Агасси');
INSERT into players (id, name) values (default, 'Сампрас');
INSERT into players (id, name) values (default, 'Сафин');
INSERT into players (id, name) values (default, 'Борг');
INSERT into players (id, name) values (default, 'Медведев');
INSERT into players (id, name) values (default, 'Кафельников');
INSERT into players (id, name) values (default, 'Беккер');
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 1, 10, 10 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 2, 9, 2 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 3, 8, 8 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 4, 7, 4 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 5, 6, 6 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 6, 5, 5 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 7, 4, 4 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 8, 3, 3 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 9, 2, 2 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 1, 1 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 2, 10 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 3, 3 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 4, 10 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 5, 5 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 10, 6, 10 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 9, 4, 4 );
INSERT into matches (id, player_one_id, player_two_id, winner_id) values (default, 8, 5, 5 );